### ISSUE TITLE
remove lambda braille table entry in GUI

### ISSUE THREAD

**Issue by albzan** [lambda-nvda/lambdaNvda#12]
- add a terminate() method inside the appmodule class,
- add a removeBrailleTableToGUI method in lambdaProfileSetup module

**Comment by nvdaes** [comment]
Sorry, I have mada a stupid mistake and reopened this fixed issue.
Thanks, great work.

**Comment by nvdaes** [comment]
Hi, unfortunately, adding a table named lambda-es.utb, this is not deleted.
Thanks.

**Comment by albzan** [comment]
Confirmed

**Comment by nvdaes** [comment]
Anyway, I think that tables should have translatable strings to be 
displayed.

I think it's better that you do changes and not reviewers.

Anyway, sometimes reviewers create for instance a branch named 
possibleImprovements for reviewed add-ons, and then authors can evaluate 
it and merge changes or consider them, since sometimes it can be easy to 
understand suggestions.

Just is a proposal, since sometimes it can be fast to think in action.

Thanks.

**Comment by nvdaes** [comment]
Thanks. I will review this.
