### ISSUE TITLE
Suggestion: Don't create an automatic profile

### ISSUE THREAD

**Issue by nvdaes** [lambda-nvda/lambdaNvda#32]
If config.conf is used, users may choose don't create a profile for Lambda. Furthermore, they could prefer to preserve previously saved options for Lambda, i.e., if they want that characters are spoken or the cursor braille shape.
A possibility maybe to add a lambda.ini file in the root of the add-on, at the same level of installTasks, and ask a question: If a new profile should be created with reccomended settings, or just continue installation.
If user say yes, the the file could be copied to profiles folder.

**Comment by nvdaes** [comment]
Or create the profile, if possible and user says yes, from the
installTasks, and the corresponding trigger. I will continue if needed
depending on your comments.
Thanks.

2017-05-15 18:45 GMT+02:00, nvdaes <notifications@github.com>:

**Comment by albzan** [comment]
Hi,
When I decided to use profiles I considered that probably it was not the right tool to adopt. Thinking to the "semantic" of profiles, you are right, users should be free to edit, create and delete profiles. 

Profiles in this addon addresses the following four requirements:
1. A ready-to-go solution: The user installs the addon and don't care about braille tables, braille word wrapping and braille tethering. Most of NVDA users completely ignores these fieatures as they ignore how profiles works. So we need to keep in mind that a Lambda users should be a 13-years-old student and her teacher who want an easy-to-install solution
2. A "factory-default" environment: This have the advantage to have the same starting point for each user so that they can follow a tutorial or a podcast and have their workplace automatically configured depending on their language (i.e. the default braille table is the default for their language). 
3. An easy "revert to default" option: If a student experiences issue after a while, she or her teacher can simply delete the profile and restart Lambda. In the same way, if a user experiences a bug, no matter on his NVDA skills, you can start the support asking "have you tried to delete the lambda profile and restart the application? Do you experience the problem again?". You are guarantee that in this way the user have, at least, a predictable configuration, so you can exclude braille settings problems.
4. It's the same behaviour they have with JAWS. If they are familiar with the JAWS scripts, here is the same. This addon is designed to make the transition as smooth as possible. We can't expect that an user who want to switch from JAWS to NVDA to read all the documentation related to the braille configuration.

About the cursor shape, speech options etc. they are consistent with the user preferences, since the default profile sets only few options. If the user experiences any inconsistency, he knows that he can simply delete the "lambda" profile and restart the application.

That's how profiles are used in this context and I don't see any other solution to address this.

What do you think?

Alberto

**Comment by nvdaes** [comment]
It makes sense. Then just ensure that features of NVDA can work
properly, even if the profile is deleted.
Personally I find the message about existing profile not enough clear.
I will prefer a single question, but maybe just a personal preference.
About braille tables, I don't know if it will be possible to map
languages with tables properly. Italian is default as a solution.
Another question: Should be tables customizable? It maybe another feature.

2017-05-15 22:29 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Hi Noelia,
Thank you for your comment.

2017-05-15 22:50 GMT+02:00 nvdaes <notifications@github.com>:

> Then just ensure that features of NVDA can work
> properly, even if the profile is deleted.
>

Yes, we need to test. When the profile is deleted a new profile will be
created after the user restarts Lambda.
The corner case is if the user deletes the profile but do not close and
re-open the editor. I think this is something like the #27, and with your
code contribution on default value for flatMode, I hope to have it solved.


> Personally I find the message about existing profile not enough clear.
> I will prefer a single question, but maybe just a personal preference.
>

Could you formulate the question. The question should not be "Do you want
to create a default profile?", because if the profile does not exists it
will be created anyway. It should be "Do you want to delete your existing
profile", but for security reason it was not my intention to delete any
user information. What do you suggest? Should I ask for a profile deletion?


> About braille tables, I don't know if it will be possible to map
> languages with tables properly. Italian is default as a solution.
>

Now they are mapped using a translation string. Who localize the addon,
localize also the braille table (or contact the person who has in charge to
translate the braille table in his language).


> Another question: Should be tables customizable? It maybe another feature.
>
Yeah, absolutly. The user should edit braille table from the addon
directory. You are right, we need to document this feature better.
And, most important, the student can edit his braille table even if he is
not the computer Administrator, which is not the case in many school labs.

Alberto

**Comment by nvdaes** [comment]
I'm testing and don't find bugs when manipulating profiles now. My
concern was mainly for users who want modify or delete the Lambda
profile, but thinking on final users, at least for now perhaps this
can be closed, or wait a little in case we find more bugs. I think
that a long message in the dialog perhaps is confusing since it's just
presented at installation.
But for me, if no bug is found, it's OK and you can close this.

2017-05-15 22:50 GMT+02:00, nvdaes <notifications@github.com>:
