### ISSUE TITLE
UX: Provide a short name for the calculator viewer

### ISSUE THREAD

**Issue by nvdaes** [lambda-nvda/lambdaNvda#33]
Users can press for example NVDA+tab and an uggly value is shown now.

**Comment by albzan** [comment]
Yeah 
That's a problem but is not easy to solve. 
An easy solution is to map NVDA+Tab.
If you change the value, than you'll read in braille:
 p equals 3 decimal point 1416 
Instead of
\pi=3,1416
I suggest you to read the row simply by pressing UP Arrow or the right command: NVDA+L (Say Line).

Alberto

**Comment by nvdaes** [comment]
OK, then close this please. Thanks.

2017-05-15 22:06 GMT+02:00, albzan <notifications@github.com>:
