### ISSUE TITLE
Provide a way to set default recommended settings in Lambda

### ISSUE THREAD

**Issue by nvdaes** [lambda-nvda/lambdaNvda#35]
A user can modify the Lambda profile for instance to change the shape cursor for the specific program. When reinstalling the add-on, s/he is invited to delete the profile so that the add-on can be configured correctly. If the profile is deleted, important options for the user could be removed when the default profile for lambda is created at start
Also, a user could accidentally change a default option used in Lambda. Then, a dialog with checkboxes with recommended default values for the few recommended options could be implemented, so that:
1. Users can see quickly the suggested settings.
2. If they want just to change these options, mostly to set them to recommended defaults, they can open the dialog and press OK.

**Comment by albzan** [comment]
Hi,
Great!
It's really a good idea so the user can press a shortcut and have this dialog to reset default values for specific setting options.
Then we can change the setup message asking the user to press this shortcut at the first startup of LAMBDA. 
We can use the gui.settingsDialogs.ReviewCursorDialog as a starting model for this dialog. By default all checkbox will be checked.
What do you think? 
Thanks
Alberto

**Comment by nvdaes** [comment]
Great. Then this settings should be saved in the Lambda profile, even
if triggers are suspended, I suppose.
Also, a combo box just with braille tables starting with Lambda can be added.
When the add-on is uninstalled, the tables disappear, but if one of
the Lambda tables is selected, the combo box doesn't have nothing
selected. I don't know if this should or can be fixed on uninstall
function, but it's a minor mater.
Thanks.

2017-05-16 10:29 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Hi Noelia,
Ok... Let's start with small steps.
For the braille table I'll add a checkbox with the default braille table
for the user language (localized string).
The text should be "Keep the LAMBDA braille table for my language (table
name)".
If a user want more options, she can, of course, open the braille settings
dialog. I don't want to duplicate existing dialogs because otherwise we
need to keep it consistent with NVDA core changes.
If a user knows he have changed his braille table, he uncheck and here he
goes.
Cheers,
Alberto


2017-05-16 11:23 GMT+02:00 nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
OK, and if the language hasn't a braille table, set Italian.
Obviously we can post the add-on without this. I don't see bugs or key
errors and basic review pass.
I'm testing with braille and this is wanderful.

2017-05-16 11:39 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Ok, We need to update the documentation. Someone want to help me on this? The shortcut to open the dialog is NVDA+ALT+R (Revert configuration).
Tnx

Alberto

**Comment by ivnc** [comment]
As I said by the group, tomorrow I could help with the documentation.  Why tomorrow?  Because I have to view carefully the changes  during this night and tomorrow's morning before updating the documentation.
 By the way, a Spanish user  of the addon sent to me by mail some books, I will report you on the next days. 

 Regards

**Comment by ivnc** [comment]
Edited: the dialog works fine, but only when focused in LAMBDA, I thought that the keystroke would work with all applications. Excuse me for the inconveniences. I'll continue testing other functionalities and the Spanish bt during the day.

Regards.

**Comment by nvdaes** [comment]
Please use the input gestures dialog under Preferences submenu of NVDA
menu, and try to change this gesture, for instance to control+shift+s
or another one. Maybe your keyboard, as some keystrokes are not always
recongized for all systems.

2017-05-18 16:49 GMT+02:00, Iván Novegil <notifications@github.com>:

**Comment by ivnc** [comment]
Edited, it works... sory so much.

**Comment by nvdaes** [comment]
Great!

2017-05-18 17:08 GMT+02:00, Iván Novegil <notifications@github.com>:
